# Generated by Django 3.2.22 on 2024-01-01 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='employeeid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.payrollemployee'),
        ),
    ]
