# Generated by Django 3.2.22 on 2024-01-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_attendance_employeeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='csourceofsupply',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='csourceofsupply',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='amtrecvd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='balance_due',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='grand_total',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
