# Generated by Django 3.2.22 on 2024-01-04 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20240103_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='employeeid',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.payrollemployee'),
        ),
    ]
