# Generated by Django 3.2.22 on 2024-01-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_attendance_employeeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='amtrecvd',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='balance_due',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='grand_total',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
