# Generated by Django 4.2.3 on 2024-01-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20240108_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='full_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='bill_no',
            field=models.CharField(default=1000, max_length=100),
        ),
    ]
