# Generated by Django 3.2.22 on 2024-01-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20240113_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_expense',
            name='vendor_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasedebit',
            name='vendor_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='vendor_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='vendor_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='balance_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='openingbalance',
            field=models.IntegerField(null=True),
        ),
    ]
