# Generated by Django 3.2.22 on 2024-01-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20240117_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='full_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='bill_no',
            field=models.CharField(default=1000, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='balance_amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='openingbalance',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
