# Generated by Django 3.2.22 on 2024-01-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20240119_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='opblnc_due',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
