# Generated by Django 3.2.22 on 2024-01-23 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20240123_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='inv_converted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.invoice'),
        ),
        migrations.AddField(
            model_name='challan',
            name='rec_converted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.recinvoice'),
        ),
    ]
