# Generated by Django 3.2.22 on 2024-01-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20240123_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment1',
            name='payments',
            field=models.FloatField(null=True),
        ),
    ]
