# Generated by Django 3.2.22 on 2024-01-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_purchasepayment1_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='amtrecvd',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='bill_no',
            field=models.CharField(default=1000, max_length=100),
        ),
    ]
