# Generated by Django 4.2.3 on 2023-11-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_auto_20231125_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='min_stock',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
