# Generated by Django 4.2.3 on 2023-12-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_itemtable_min_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedebit',
            name='file',
            field=models.FileField(default='default.jpg', upload_to='sales'),
        ),
    ]
