# Generated by Django 4.2.3 on 2023-12-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_purchasedebit_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedebit',
            name='gstnumber',
            field=models.CharField(default='NULL', max_length=150),
        ),
        migrations.AddField(
            model_name='purchasedebit',
            name='gsttype',
            field=models.CharField(default='NULL', max_length=150),
        ),
    ]
