# Generated by Django 3.2.22 on 2023-12-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_auto_20231213_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment1',
            name='payment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasepayment1',
            name='payment_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
