# Generated by Django 4.2.3 on 2023-12-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0051_auto_20231216_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedebit',
            name='cheque_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchasedebit',
            name='upi_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
