# Generated by Django 3.2.22 on 2023-12-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0051_auto_20231216_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='converted_inv',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='challan',
            name='converted_rec',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='challanitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.itemtable'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pay_method',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='price_list',
            field=models.IntegerField(null=True),
        ),
    ]
