# Generated by Django 3.2.22 on 2023-12-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_attendance_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedebit',
            name='cheque_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchasedebit',
            name='upi_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
