# Generated by Django 4.2.3 on 2023-12-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_auto_20231222_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedebit',
            name='debit_no',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
